services:
  - type: web
    name: trexim-v4
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --chdir /opt/render/project/src
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
